-- Energy Insights Platform schema
-- This file is executed by the platform's DB init process (if configured to run *.sql in .init).

CREATE TABLE IF NOT EXISTS sites (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  customer_name VARCHAR(255) NOT NULL,
  timezone VARCHAR(64) NOT NULL DEFAULT 'UTC',
  sqft INT NULL,
  industry VARCHAR(128) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_sites_customer_name (customer_name)
) ENGINE=InnoDB;

-- Optional grouping for benchmarking (e.g., "Retail - Northeast", "Warehouses")
CREATE TABLE IF NOT EXISTS benchmark_groups (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_benchmark_groups_name (name)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS site_benchmark_groups (
  site_id BIGINT UNSIGNED NOT NULL,
  benchmark_group_id BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (site_id, benchmark_group_id),
  CONSTRAINT fk_sbg_site FOREIGN KEY (site_id) REFERENCES sites(id) ON DELETE CASCADE,
  CONSTRAINT fk_sbg_group FOREIGN KEY (benchmark_group_id) REFERENCES benchmark_groups(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Interval meter data (15-min or hourly, etc.)
CREATE TABLE IF NOT EXISTS interval_readings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  site_id BIGINT UNSIGNED NOT NULL,
  meter_id VARCHAR(128) NOT NULL,
  ts DATETIME NOT NULL,
  kwh DECIMAL(12,4) NOT NULL,
  demand_kw DECIMAL(12,4) NULL,
  quality_flag VARCHAR(32) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_interval_site FOREIGN KEY (site_id) REFERENCES sites(id) ON DELETE CASCADE,
  UNIQUE KEY uq_interval (site_id, meter_id, ts),
  INDEX idx_interval_site_ts (site_id, ts)
) ENGINE=InnoDB;

-- Simple anomaly/alert records generated by backend
CREATE TABLE IF NOT EXISTS anomaly_alerts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  site_id BIGINT UNSIGNED NOT NULL,
  meter_id VARCHAR(128) NOT NULL,
  ts DATETIME NOT NULL,
  severity ENUM('low','medium','high') NOT NULL,
  alert_type VARCHAR(64) NOT NULL, -- e.g. "spike", "drop", "missing"
  title VARCHAR(255) NOT NULL,
  details TEXT NULL,
  acknowledged TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_alert_site FOREIGN KEY (site_id) REFERENCES sites(id) ON DELETE CASCADE,
  INDEX idx_alert_site_ts (site_id, ts),
  INDEX idx_alert_ack (acknowledged)
) ENGINE=InnoDB;

-- Seed a couple benchmark groups for demo purposes
INSERT IGNORE INTO benchmark_groups (name, description)
VALUES
  ('Retail', 'Retail stores benchmark group'),
  ('Warehouse', 'Warehouse / logistics facilities benchmark group');
